baseURL = "https:/funbohe.com/"
disqusShortname = "sicily-hugo-theme"
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "10"
summaryLength = "15"
theme = "Sicily-hugo-theme"
title = "FUNBOHE"
[markup.goldmark.renderer]
unsafe = true
[[menu.company]]
URL = "about-us"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "WORKS"
weight = 1
[params]
author = "FUNBOHE"
contact_form_action = "#"
description = "This is meta description"
footer = []
logo = "images/logo.png"
logo_width = "200px"
[params.company]
address = "7657 Cl. 6, Centro"
city = "Kunming"
country = "China"
email = "funbohe@gmail.com"
phone = "+86 18184889953"
[params.navigation_button]
enable = false
label = "Get it touch"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/custom/clean-footer.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/cristianmarint"
title = "twitter"
[[params.social]]
icon = "ti-skype"
link = "#"
title = "skype"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
